### ISSUE TITLE
libgtkglext-x11 missing

### ISSUE THREAD

**Issue by probonopd** [regeya/upwork-appimage#1]
On Ubuntu 16.04 LTS I get:

```
/home/me/Downloads/Upwork.AppImage: error while loading shared libraries: libgtkglext-x11-1.0.so.0: cannot open shared object file: No such file or directory
```

Possibly this library (package `libgtkglext1`) should be bundled inside the AppImage.

**Comment by regeya** [comment]
OK, thanks!  I explicitly added that to the script.

Next...I need to figure out why it got left out in the first place. :-/

**Comment by probonopd** [comment]
Did you know that you can test easily with [testappimage](https://github.com/probonopd/AppImageKit/blob/master/AppImageAssistant.AppDir/testappimage)?

Like this: `sudo testappimage some-ubuntu-live.iso Your.AppImage`

**Comment by regeya** [comment]
Thanks for the heads-up on that; thanks to testappimage, I added libgdkglext.

BTW, I just want to say a big thanks for AppImage.  I've been doing some side hustles with Upwork, and using it on Arch Linux can be troublesome; this has been a lifesaver.

**Comment by probonopd** [comment]
Thanks @regeya
Btw, I noticed you are doing quite a lot to generate the AppImage, maybe you'd be interested in a somewhat leaner way: 

https://github.com/probonopd/AppImages/blob/master/recipes/upwork/Recipe
I am running this on Travis CI to automatically generate the AppImage in the cloud.

Also, are you sure you need to bundle all the libs that you are currently bundling and cannot assume more of them to be present on the target systems? (The answer to this question depends largely on the selection of systems you are targeting.)

**Comment by regeya** [comment]
Thanks, probonopd.  I know it's been more than a month since you uploaded that, and I'm just now taking a look at it.  I wasn't aware of the automatic installation of desktop files, which eliminates the need for an Arch installer.  I did notice, though, from running it on my local machine that it doesn't seem to build a working app, at least not for me.  Unfortunately, Upwork stubbornly brings in old dependencies which I wish they wouldn't, but in order to be able to use the app to make some side income, I need to have working.  I'll try to figure out what the problem is and will let you know.
